---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-single
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-single
      targetRevision: 0.12.*
      helm:
        valueFiles:
          - $values/core-cluster/values/victoria-metrics-single.yaml
    - repoURL: https://github.com/iamtahmad1/monitoring.git
      targetRevision: HEAD
      ref: values
